export const SIGNATURE_TYPES = [
  {
    id: 1,
    signatureType: 'Manager and Location',
    nameSupermarketManager: true,
    nameAssistantManager: false,
    title: true,
    street: true,
    houseNumber: true,
    cityAsTitle: false,
    city: true,
    phone: true,
    email: true,
    entrepreneur: false
  },
  {
    id: 2,
    signatureType: 'Assistent​ ​manager​ ​+​ ​location',
    nameSupermarketManager: false,
    nameAssistantManager: true,
    title: true,
    street: true,
    houseNumber: true,
    cityAsTitle: false,
    city: true,
    phone: true,
    email: true,
    entrepreneur: false
  },
  {
    id: 3,
    signatureType: 'City',
    nameSupermarketManager: false,
    nameAssistantManager: false,
    title: false,
    street: true,
    houseNumber: true,
    cityAsTitle: true,
    city: true,
    phone: true,
    email: true,
    entrepreneur: false
  },
  {
    id: 4,
    signatureType: 'Street​ ​+​ ​housenumber​ ​+​ ​City',
    nameSupermarketManager: false,
    nameAssistantManager: false,
    title: false,
    street: true,
    houseNumber: true,
    cityAsTitle: false,
    city: true,
    phone: true,
    email: true,
    entrepreneur: false
  },
  {
    id: 5,
    signatureType: 'Manager​ ​+​ ​Assistent​ ​+​ ​City',
    nameSupermarketManager: true,
    nameAssistantManager: true,
    title: false,
    street: true,
    houseNumber: true,
    cityAsTitle: true,
    city: true,
    phone: true,
    email: true,
    entrepreneur: false
  },
  {
    id: 6,
    signatureType: 'Manager​ ​(ondernemer)​ ​+​ ​City',
    nameSupermarketManager: true,
    nameAssistantManager: false,
    title: false,
    street: true,
    houseNumber: true,
    cityAsTitle: false,
    city: true,
    phone: true,
    email: true,
    entrepreneur: true
  },
  {
    id: 7,
    signatureType: 'Manager​ ​(ondernemer)​ ​+​ ​Asisstent​ ​+​ ​City',
    nameSupermarketManager: true,
    nameAssistantManager: true,
    title: false,
    street: true,
    houseNumber: true,
    cityAsTitle: false,
    city: true,
    phone: true,
    email: true,
    entrepreneur: true
  },
  {
    id: 8,
    signatureType: 'Write​ ​your​ ​own​ ​signature',
    nameSupermarketManager: false,
    nameAssistantManager: false,
    title: false,
    street: false,
    houseNumber: false,
    cityAsTitle: false,
    city: false,
    phone: false,
    email: false,
    entrepreneur: false
  }
];
